apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flights
  name: flights
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flights
  strategy: {}
  template:
    metadata:
      labels:
        app: flights
    spec:
      containers:
      - name: flights
        image: ${APP_USER}/flights:v1
        env:
          - name: Flights_Kiwi
            valueFrom:
              configMapKeyRef:
                name: flight-app-config
                key: Flights_Kiwi
          - name: Kiwi_api_call
            valueFrom:
              configMapKeyRef:
                name: flight-app-config
                key: Kiwi_api_call
        ports:
        - containerPort: 8081
          name: rest-port
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: flights
  labels:
    app: flights
spec:
  type: ClusterIP
  selector:
    app: flights
  ports:
  - name: rest
    port: 81
    targetPort: rest-port