apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notifications
  strategy: {}
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - name: notifications
        image: ${APP_USER}/notifications:v1
        ports:
        - containerPort: 8087
          name: rest-port
---
apiVersion: v1
kind: Service
metadata:
  name: notifications
  labels:
    app: notifications
spec:
  type: ClusterIP
  selector:
    app: notifications
  ports:
  - name: rest
    port: 87
    targetPort: rest-port