apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment
  name: payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  strategy: {}
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: ${APP_USER}/payment:v1
        ports:
        - containerPort: 8084
          name: rest-port
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
spec:
  type: ClusterIP
  selector:
    app: payment
  ports:
  - name: rest
    port: 84
    targetPort: rest-port