apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: seating
  name: seating
spec:
  replicas: 2
  selector:
    matchLabels:
      app: seating
  strategy: {}
  template:
    metadata:
      labels:
        app: seating
    spec:
      containers:
      - name: seating
        image: mbirnhak/seating:v1
        ports:
        - containerPort: 8086
          name: rest-port
---
apiVersion: v1
kind: Service
metadata:
  name: seating
  labels:
    app: seating
spec:
  type: NodePort
  selector:
    app: seating
  ports:
  - name: rest
    port: 86
    targetPort: rest-port
    nodePort: 30105