apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transactionservice
  name: transactionservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transactionservice
  strategy: {}
  template:
    metadata:
      labels:
        app: transactionservice
    spec:
      containers:
      - name: transactionservice
        image: mbirnhak/transactionservice:v1
        ports:
        - containerPort: 8082
          name: rest-port
        env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: flight-app-config  
                  key: MONGO_DB
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: flight-app-config 
                  key: MONGO_HOST
            - name: MONGO_AUTH_DB
              valueFrom:
                configMapKeyRef:
                  name: flight-app-config 
                  key: MONGO_AUTH_DB
---
apiVersion: v1
kind: Service
metadata:
  name: transactionservice
  labels:
    app: transactionservice
spec:
  type: NodePort
  selector:
    app: transactionservice
  ports:
  - name: rest
    port: 82
    targetPort: rest-port
    nodePort: 30109