apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transactionservice
  name: transactionservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transactionservice
  strategy: {}
  template:
    metadata:
      labels:
        app: transactionservice
    spec:
      containers:
      - name: transactionservice
        image: mbirnhak/transactionservice:v1
        ports:
        - containerPort: 8082
          name: rest-port
---
apiVersion: v1
kind: Service
metadata:
  name: transactionservice
  labels:
    app: transactionservice
spec:
  type: ClusterIP
  selector:
    app: transactionservice
  ports:
  - name: rest
    port: 82
    targetPort: rest-port