apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: userservice
  name: userservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userservice
  strategy: {}
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
      - name: userservice
        image: mbirnhak/userservice:v1
        ports:
        - containerPort: 8083
          name: rest-port
---
apiVersion: v1
kind: Service
metadata:
  name: userservice
  labels:
    app: userservice
spec:
  type: NodePort
  selector:
    app: userservice
  ports:
  - name: rest
    port: 83
    targetPort: rest-port
    nodePort: 30103