apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: seating
  name: seating
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seating
  strategy: {}
  template:
    metadata:
      labels:
        app: seating
    spec:
      containers:
      - name: seating
        image: ${APP_USER}/seating:v1
        env:
            - name: SEATING_MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: flight-app-config  
                  key: MONGO_DB
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: flight-app-config 
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                  configMapKeyRef:
                    name: flight-app-config 
                    key: MONGO_PORT
        ports:
        - containerPort: 8086
          name: rest-port
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "128Mi"
        
---
apiVersion: v1
kind: Service
metadata:
  name: seating
  labels:
    app: seating
spec:
  type: ClusterIP
  selector:
    app: seating
  ports:
  - name: rest
    port: 86
    targetPort: rest-port