apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: userservice
  name: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
      - name: userservice
        image: ${APP_USER}/userservice:v1
        env:
            - name: USER_MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: flight-app-config  
                  key: USER_MONGO_DB
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: flight-app-config 
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: flight-app-config 
                  key: MONGO_PORT 
        ports:
        - containerPort: 8083
          name: rest-port
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "128Mi"
        
---
apiVersion: v1
kind: Service
metadata:
  name: userservice
  labels:
    app: userservice
spec:
  type: ClusterIP
  selector:
    app: userservice
  ports:
  - name: rest
    port: 83
    targetPort: rest-port